<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_txt</name>
   <tag></tag>
   <elementGuidId>3f5c7e2a-62cd-45e5-823c-fbfadce1c9c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form-validator-apply&quot;]/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form-validator-apply&quot;]/div/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
