<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Experience_txt</name>
   <tag></tag>
   <elementGuidId>e513e127-2234-4633-a3f1-ecff6dcdbbfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form-validator-apply&quot;]/div/div[10]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form-validator-apply&quot;]/div/div[10]/div/textarea</value>
   </webElementProperties>
</WebElementEntity>
