<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Joinschool_btn</name>
   <tag></tag>
   <elementGuidId>ee7c2d75-500b-492a-a342-4a8b28c1c9e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section[3]/div/div[2]/div/div[2]/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[3]/div/div[2]/div/div[2]/div/div[2]/a</value>
   </webElementProperties>
</WebElementEntity>
