<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>register_btn</name>
   <tag></tag>
   <elementGuidId>c4a261d2-a501-49ec-8d0f-17810b472d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sign_in&quot;]/div/div/div[2]/div/form/div[5]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sign_in&quot;]/div/div/div[2]/div/form/div[5]/button</value>
   </webElementProperties>
</WebElementEntity>
