<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home_search_btn</name>
   <tag></tag>
   <elementGuidId>7539c66e-e2b4-4acd-b194-71feca7bc3eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section[3]/div/div/div[1]/div/div/form/div[5]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[3]/div/div/div[1]/div/div/form/div[5]/div/button</value>
   </webElementProperties>
</WebElementEntity>
