<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>school_insta</name>
   <tag></tag>
   <elementGuidId>93047a08-d07f-4ecf-b2a0-bcdb29e04e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form-validator&quot;]/div/div[19]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form-validator&quot;]/div/div[19]/div/input</value>
   </webElementProperties>
</WebElementEntity>
