<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>teachers</name>
   <tag></tag>
   <elementGuidId>4b0e24b0-165f-4abd-8dfe-d5a231930ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;form-validator&quot;]/div/div[31]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;form-validator&quot;]/div/div[31]/div/input</value>
   </webElementProperties>
</WebElementEntity>
