<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_review_btn</name>
   <tag></tag>
   <elementGuidId>e482cdc9-b07e-46d6-b77d-40ed46233de4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;displayReviews&quot;]/div/div/div[3]/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;displayReviews&quot;]/div/div/div[3]/div/button/i</value>
   </webElementProperties>
</WebElementEntity>
