<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>numbers_btn</name>
   <tag></tag>
   <elementGuidId>d2e5bd5b-e486-4da5-855b-5606ea9df075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dataContainer&quot;]/div[11]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dataContainer&quot;]/div[11]/ul/li[4]/a</value>
   </webElementProperties>
</WebElementEntity>
