<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>schools_btn</name>
   <tag></tag>
   <elementGuidId>81f1db7a-7ea4-4d9f-8b23-af703eca7907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-navbar-collapse2&quot;]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-navbar-collapse2&quot;]/ul/li[2]/a</value>
   </webElementProperties>
</WebElementEntity>
