<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_by_name</name>
   <tag></tag>
   <elementGuidId>08ec7c22-ca65-45c9-b38f-83c6010fbb31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section[3]/div/div/div[1]/div/div/form/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[3]/div/div/div[1]/div/div/form/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
