<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_btn</name>
   <tag></tag>
   <elementGuidId>952aae94-b3de-49f4-8ea9-7afdf940c8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-navbar-collapse&quot;]/ul[2]/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-navbar-collapse&quot;]/ul[2]/li[3]/a</value>
   </webElementProperties>
</WebElementEntity>
