<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>register_btn</name>
   <tag></tag>
   <elementGuidId>7a4ba1db-a058-4ca4-97b6-4c0ea9da5f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sign_in&quot;]/div/div/div[2]/div/div[2]/form/div[5]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sign_in&quot;]/div/div/div[2]/div/div[2]/form/div[5]/div/button</value>
   </webElementProperties>
</WebElementEntity>
