<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wordpress_course</name>
   <tag></tag>
   <elementGuidId>3946d9e3-bda4-4d71-ac1f-df2c2bde9941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section[3]/div/div/div[2]/div/div/div[1]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[3]/div/div/div[2]/div/div/div[1]/div/a/img</value>
   </webElementProperties>
</WebElementEntity>
